name: schoolmanagement
description: A new Flutter project.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.4
  uuid: ^4.1.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
